# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoGame

pod 'IQKeyboardManager'
pod 'Firebase'
pod 'FirebaseCore'
pod 'FirebaseDatabase'
pod 'FirebaseFirestore'
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Dialogs'

  target 'DemoGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoGameUITests' do
    # Pods for testing
  end

end
